name: CI

on:
  push:
    branches: [ main, master, lint ]
  pull_request:
    branches: [ main, master, lint ]

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Set the runner runtime directly
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript Linter
        run: npm run lint